language: python

matrix:
    include:
        - os: linux
          python: 3.4
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3
        - os: linux
          python: 3.5
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3
        - os: linux
          python: 3.6
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3
        - os: linux
          python: 3.7
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3
          dist: xenial
        - os: linux
          python: 3.8
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3
          dist: xenial
        - os: linux
          python: pypy3
          env: PYTHON=python PIP=pip BAP=rfclint/linux
        - os: osx
          language: generic
          env: TOXENV=py36 PYTHON=python3 PIP=pip3 BAP=rfclint/macos

script:
  - $PIP install pycodestyle
  - $PIP install pyflakes
  - export PATH=$PATH:${HOME}/build/Com-AugustCellars/Rfc-Errata/$BAP
  - pwd
  - $PYTHON --version
  - $PYTHON setup.py --quiet install
  - pwd
  - cd errata && $PYTHON test.py
